'use client';
import {useState,useEffect} from 'react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
type Booking={id:string;name:string;email:string;phone:string;arrival:string;departure:string;guests:number;note:string;status:string};
export default function Admin(){const [rows,setRows]=useState<Booking[]>([]),[blocked,setBlocked]=useState<{day:string}[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[cancel,setCancel]=useState<Booking|null>(null);
async function load(){try{const r=await fetch('/api/admin');const d=await r.json() as {error:string;bookings:Booking[];blocked:{day:string}[]};if(!r.ok)throw Error(d.error);setRows(d.bookings);setBlocked(d.blocked);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{load();},[]);
async function act(body:object){setBusy(true);setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error:string;bookings:Booking[];blocked:{day:string}[]};if(!r.ok)throw Error(d.error);await load();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
return <><header className="header"><a className="brand" href="/">green<span>&</span>blue<small>OWNER DASHBOARD</small></a><a href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a></header><main className="admin"><p className="eyebrow">THE PORTSIDE · KASTELLA</p><h1>Your stays, in one place.</h1><p>Review requests, confirm reservations and manage unavailable dates. Contact guests directly to agree the price before confirming.</p><div className="stats">{['pending','confirmed','cancelled'].map(s=><div key={s}><strong>{rows.filter(r=>r.status===s).length}</strong><span>{s}</span></div>)}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="section-heading"><h2>Reservations</h2><button onClick={load} disabled={busy}>Refresh</button></div>{loading?<p>Loading reservations…</p>:rows.length===0?<div className="empty">No booking requests yet. New requests from your website will appear here.</div>:<Table><TableHeader><TableRow>{['Guest','Stay','Status','Actions'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id}><TableCell><strong>{r.name}</strong><br/><a href={'mailto:'+r.email}>{r.email}</a><br/><a href={'tel:'+r.phone}>{r.phone}</a>{r.note&&<p className="guest-note">{r.note}</p>}</TableCell><TableCell>{r.arrival}<br/>{r.departure}<br/>{r.guests} guests</TableCell><TableCell><span className={'status '+r.status}>{r.status}</span></TableCell><TableCell><div className="actions">{r.status==='pending'&&<button className="button" disabled={busy} onClick={()=>act({action:'confirm',id:r.id})}>Confirm</button>}{r.status!=='cancelled'&&<button disabled={busy} onClick={()=>setCancel(r)}>Cancel</button>}</div></TableCell></TableRow>)}</TableBody></Table>}
<section className="block-section"><h2>Manage unavailable dates</h2><p>Block Airbnb stays and owner use here. This calendar does not automatically sync with Airbnb.</p><form className="block-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await act({action:'block',arrival:f.get('arrival'),departure:f.get('departure')});}}><label>From<input required name="arrival" type="date"/></label><label>Until (checkout day)<input required name="departure" type="date"/></label><button className="button" disabled={busy}>Block dates</button></form><div className="blocked">{blocked.map(b=><button key={b.day} disabled={busy} onClick={()=>act({action:'unblock',day:b.day})} aria-label={'Unblock '+b.day}>{b.day} ×</button>)}</div></section></main><AlertDialog open={!!cancel} onOpenChange={()=>setCancel(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancel this reservation?</AlertDialogTitle><AlertDialogDescription>This releases the dates for {cancel?.name}. Please contact the guest directly; no automatic email is sent.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep reservation</AlertDialogCancel><AlertDialogAction onClick={()=>act({action:'cancel',id:cancel?.id})}>Cancel reservation</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

