'use client';
import {useState,useEffect} from 'react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import OwnerCalendar,{type Booking,type Night} from './owner-calendar';
import {suites,findSuite} from '@/lib/suites';
type Payload={error?:string;today:string;end:string;bookings:Booking[];nights:Night[]};
export default function Admin(){
 const [rows,setRows]=useState<Booking[]>([]),[nights,setNights]=useState<Night[]>([]),[range,setRange]=useState({today:'',end:''}),[suite,setSuite]=useState(suites[0]),[filter,setFilter]=useState('all');
 const [error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[cancel,setCancel]=useState<Booking|null>(null);
 async function load(){try{const r=await fetch('/api/admin',{cache:'no-store'});const d=await r.json() as Payload;if(!r.ok)throw Error(d.error);setRows(d.bookings);setNights(d.nights);setRange({today:d.today,end:d.end});}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function act(body:object){setBusy(true);setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await load();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const visible=filter==='all'?rows:rows.filter(r=>r.suite===filter);
 return <><header className="header"><a className="brand" href="/">green<span>&</span>blue<small>OWNER DASHBOARD</small></a><button className="signout" onClick={async()=>{await fetch("/api/admin/logout",{method:"POST"});location.href="/";}}>Sign out</button></header>
 <main className="admin"><p className="eyebrow">GREEN & BLUE · KASTELLA</p><h1>Your stays, in one place.</h1><p>Review requests, confirm reservations and manage availability for all three suites. Contact guests directly to agree the price before confirming.</p>
 <div className="stats">{['pending','confirmed','cancelled'].map(s=><div key={s}><strong>{rows.filter(r=>r.status===s).length}</strong><span>{s}</span></div>)}</div>
 {error&&<p className="error" role="alert">{error}</p>}
 <section className="owner-section"><div className="section-heading"><h2>Availability calendar</h2><div className="tabs" role="tablist">{suites.map(s=><button key={s.slug} role="tab" aria-selected={s.slug===suite.slug} className={s.slug===suite.slug?'active':''} onClick={()=>setSuite(s)}>{s.name}</button>)}</div></div>
 <p>Block Airbnb stays or owner use straight on the calendar. Confirmed website reservations appear automatically. This calendar does not sync with Airbnb by itself.</p>
 {loading?<p>Loading calendar…</p>:<OwnerCalendar suite={suite} nights={nights} bookings={rows} today={range.today} end={range.end} busy={busy} onAction={act}/>}
 <form className="block-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')||'block';await act({action,suite:suite.slug,arrival:f.get('arrival'),departure:f.get('departure')});}}>
 <label>From<input required name="arrival" type="date"/></label><label>Until (checkout day)<input required name="departure" type="date"/></label><button className="button" value="block" disabled={busy}>Block dates</button><button className="button outline" value="unblock" disabled={busy}>Release blocks</button><span className="block-hint">Applies to {suite.name}.</span>
 </form></section>
 <section className="owner-section"><div className="section-heading"><h2>Reservations</h2><div className="actions"><select aria-label="Filter by suite" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All suites</option>{suites.map(s=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select><button onClick={load} disabled={busy}>Refresh</button></div></div>
 {loading?<p>Loading reservations…</p>:visible.length===0?<div className="empty">No booking requests yet. New requests from your website will appear here.</div>:<Table><TableHeader><TableRow>{['Guest','Suite','Stay','Status','Actions'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(r=><TableRow key={r.id}><TableCell><strong>{r.name}</strong><br/><a href={'mailto:'+r.email}>{r.email}</a><br/><a href={'tel:'+r.phone}>{r.phone}</a>{r.note&&<p className="guest-note">{r.note}</p>}</TableCell><TableCell><span className="suite-tag">{findSuite(r.suite)?.name||r.suite}</span></TableCell><TableCell>{r.arrival}<br/>{r.departure}<br/>{r.guests} {r.guests===1?'guest':'guests'}</TableCell><TableCell><span className={'status '+r.status}>{r.status}</span></TableCell><TableCell><div className="actions">{r.status==='pending'&&<button className="button" disabled={busy} onClick={()=>act({action:'confirm',id:r.id})}>Confirm</button>}{r.status!=='cancelled'&&<button disabled={busy} onClick={()=>setCancel(r)}>Cancel</button>}</div></TableCell></TableRow>)}</TableBody></Table>}
 </section></main>
 <AlertDialog open={!!cancel} onOpenChange={()=>setCancel(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancel this reservation?</AlertDialogTitle><AlertDialogDescription>This releases the dates for {cancel?.name} in {findSuite(cancel?.suite)?.name}. Please contact the guest directly; no automatic email is sent.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep reservation</AlertDialogCancel><AlertDialogAction onClick={()=>act({action:'cancel',id:cancel?.id})}>Cancel reservation</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
