'use client';
import { useState } from 'react';
import StayCalendar from './stay-calendar';
import { useLang, LanguageGate, LanguageToggle } from './language';
import { suites, type Suite } from '@/lib/suites';
import { locale } from '@/lib/i18n';
import { pretty } from '@/lib/stay-dates';
import { ArrowUpRight, ArrowRight, MapPin, Wifi, Wind, Coffee, KeyRound, BedDouble, Users, Expand, Check, Phone, Bath, ChevronLeft, ChevronRight, Images } from 'lucide-react';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const img = (s: Suite, i: number) => '/images/' + s.photos[i].file;
const AMENITY_ICONS = [Wifi, Wind, Coffee, KeyRound];
export default function Home(){
const {lang,t}=useLang();
const [suite,setSuiteState]=useState<Suite>(suites[0]),[arrival,setArrival]=useState(''),[departure,setDeparture]=useState(''),[guests,setGuests]=useState('2'),[open,setOpen]=useState(false),[view,setView]=useState<{suite:Suite;index:number}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reference,setReference]=useState('');
function setSuite(s:Suite){setSuiteState(s);setMessage('');if(Number(guests)>s.guests)setGuests(String(s.guests));}
function chooseSuite(s:Suite){setSuite(s);document.getElementById('booking')?.scrollIntoView({behavior:'smooth',block:'start'});}
const step=(n:number)=>setView(v=>v&&{...v,index:(v.index+n+v.suite.photos.length)%v.suite.photos.length});
async function availability(e:React.FormEvent){e.preventDefault();if(!arrival||!departure){setMessage(t.booking.pickFirst);return;}setBusy(true);setMessage('');try{const r=await fetch(`/api/availability?suite=${suite.slug}&arrival=${arrival}&departure=${departure}&lang=${lang}`);const d=await r.json() as {error:string;available?:boolean};if(!r.ok)throw Error(d.error);if(!d.available)throw Error(t.booking.unavailable(suite.name));setReference('');setOpen(true);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
async function reserve(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lang,suite:suite.slug,arrival,departure,guests:Number(guests),name:f.get('name'),email:f.get('email'),phone:f.get('phone'),note:f.get('note')})});const d=await r.json() as {error:string;id:string};if(!r.ok)throw Error(d.error);setReference(d.id);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
const hero=suites[0];
return <><LanguageGate/><header className="header"><a className="brand" href="/">green<span>&</span>blue<small>LUXURY SUITES · KASTELLA</small></a><nav aria-label="Main navigation"><a href="#suites">{t.nav.suites}</a>{suites.map(s=><a key={s.slug} href={'#'+s.slug}>{s.short}</a>)}<a href="#location">{t.nav.kastella}</a></nav><div className="header-right"><a className="nav-book" href="#booking">{t.nav.plan} <ArrowUpRight size={17}/></a><LanguageToggle/></div></header>
<main><section className="hero"><div className="hero-copy"><p className="eyebrow">{t.hero.eyebrow}</p><h1>{t.hero.title[0]}<br/>{t.hero.title[1]}<br/><em>{t.hero.title[2]}</em></h1><p className="hero-description">{t.hero.desc1}<br/>{t.hero.desc2}<br className="desktop"/> {t.hero.desc3}</p><a className="text-link" href="#suites">{t.hero.cta} <ArrowRight size={18}/></a><div className="hero-location"><MapPin size={16}/> {t.hero.location}</div></div><div className="hero-photo"><img src={img(hero,hero.cover)} alt={hero.photos[hero.cover].alt} fetchPriority="high"/><span className="photo-caption">{t.hero.caption} <span>01 / 03</span></span><button type="button" className="photo-badge" onClick={()=>setView({suite:hero,index:hero.cover})}><Expand size={18}/> {t.hero.explore}</button></div></section>
<section id="booking" className="booking-wrap"><div className="booking-intro"><p className="eyebrow">{t.booking.eyebrow}</p><h2>{t.booking.title}</h2></div><form className="booking-bar" onSubmit={availability}>
<div className="suite-field"><label>{t.booking.suite}</label><Select value={suite.slug} onValueChange={v=>{const s=suites.find(x=>x.slug===v);if(s)setSuite(s);}}><SelectTrigger aria-label={t.booking.suite}><SelectValue/></SelectTrigger><SelectContent>{suites.map(s=><SelectItem value={s.slug} key={s.slug}>{s.name}</SelectItem>)}</SelectContent></Select></div>
<StayCalendar suite={suite} arrival={arrival} departure={departure} onChange={(a,b)=>{setArrival(a);setDeparture(b);setMessage('');}}/>
<div className="guest-field"><label>{t.booking.guests}</label><Select value={guests} onValueChange={setGuests}><SelectTrigger aria-label={t.booking.guests}><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:suite.guests},(_,i)=>String(i+1)).map(n=><SelectItem value={n} key={n}>{t.booking.guest(Number(n))}</SelectItem>)}</SelectContent></Select></div>
<button className="button" disabled={busy}>{busy?t.booking.checking:t.booking.check}<ArrowUpRight size={18}/></button></form>
<p className="booking-note">{t.booking.note(suite.name)}</p>{message&&!open&&<p role="alert" className="error">{message}</p>}</section>
<section id="suites" className="suites-head section"><p className="eyebrow">{t.suites.eyebrow}</p><h2>{t.suites.title}<br/><em>{t.suites.titleEm}</em></h2><p>{t.suites.intro}</p><nav className="suite-jump" aria-label={t.nav.suites}>{suites.map((s,i)=><a key={s.slug} href={'#'+s.slug}><span>0{i+1}</span>{s.name}</a>)}</nav></section>
{suites.map((s,i)=>{const x=s.text[lang];return <article key={s.slug} id={s.slug} className="suite-block section">
<div className="suite-intro"><div><p className="eyebrow">{x.eyebrow}</p><h2>{x.tagline}<br/><em>{x.taglineEm}</em></h2><p className="suite-kicker">0{i+1} · {s.name} · {t.suites.rating(s.rating)}</p></div>
<div><p>{x.summary}</p><div className="facts"><span><Expand/>{t.suites.size(s.size)}</span><span><Users/>{t.suites.guests(s.guests)}</span><span><BedDouble/>{x.beds}</span><span><Bath/>{t.suites.bath(s.baths)}</span></div><ul className="highlights">{x.highlights.map(h=><li key={h}><Check size={15}/>{h}</li>)}</ul><div className="suite-links"><button type="button" className="button" onClick={()=>chooseSuite(s)}>{t.suites.dates} <ArrowUpRight size={18}/></button><a href={s.airbnb} target="_blank" rel="noreferrer" className="text-link">{t.suites.airbnb} <ArrowUpRight size={17}/></a></div></div></div>
<div className="gallery-grid">{s.grid.map((p,j)=><button type="button" key={p} className={'gallery-item image-'+j} onClick={()=>setView({suite:s,index:p})} aria-label={`${t.suites.openPhoto}: ${s.photos[p].alt}`}><img loading={i===0&&j===0?'eager':'lazy'} src={img(s,p)} alt={s.photos[p].alt}/></button>)}<button type="button" className="gallery-all" onClick={()=>setView({suite:s,index:0})}><Images size={16}/> {t.suites.allPhotos(s.photos.length)}</button></div>
<div className="suite-about">{x.description.map((p,j)=><p key={j}>{p}</p>)}</div>
</article>;})}
<section className="amenities section"><p className="eyebrow">{t.amenities.eyebrow}</p><div>{t.amenities.items.map(([title,sub],i)=>{const I=AMENITY_ICONS[i];return <article key={title}><I strokeWidth={1.2}/><h3>{title}</h3><p>{sub}</p></article>;})}</div></section>
<section id="location" className="location section"><div className="location-name"><p className="eyebrow">{t.location.eyebrow}</p><h2>{t.location.title}<br/><em>{t.location.titleEm}</em></h2><span>{t.location.deco}</span></div><div><p>{t.location.text}</p>{t.location.places.map(([name,desc],i)=><div className="places" key={name}><span>0{i+1}</span><div><h3>{name}</h3><p>{desc}</p></div></div>)}<a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Riga+Fereou+28+Pireas+185+33" target="_blank" rel="noreferrer">{t.location.address} <ArrowUpRight size={18}/></a></div></section>
<section className="closing"><p className="eyebrow">{t.closing.eyebrow}</p><h2>{t.closing.title}<br/><em>{t.closing.titleEm}</em></h2><a className="button light" href="#booking">{t.closing.cta} <ArrowUpRight size={18}/></a><a href="tel:+306946778666" className="call"><Phone size={16}/> +30 694 677 8666</a></section></main>
<footer><a className="brand" href="/">green<span>&</span>blue<small>LUXURY SUITES · KASTELLA</small></a><p>{t.footer.address}<br/><small>{t.footer.registration}: 00003061932</small></p><div>{suites.map(s=><a key={s.slug} href={s.airbnb} target="_blank" rel="noreferrer">{t.footer.onAirbnb(s.short)} <ArrowUpRight size={14}/></a>)}<a href="/admin">{t.footer.owner}</a></div></footer>
<Dialog open={open} onOpenChange={v=>{setOpen(v);setMessage('');}}><DialogContent className="booking-dialog"><DialogHeader><DialogTitle>{reference?t.request.sent:t.request.title}</DialogTitle><DialogDescription>{reference?t.request.sentText:`${pretty(arrival,'',locale(lang))} → ${pretty(departure,'',locale(lang))} · ${t.booking.guest(Number(guests))} · ${suite.name}`}</DialogDescription></DialogHeader>{reference?<div className="success"><Check/><p>{t.request.received}</p><small>{t.request.reference}: {reference}</small><a className="button" href="tel:+306946778666">{t.request.call}</a></div>:<form onSubmit={reserve} className="request-form"><p>{t.request.intro(suite.name)}</p><label>{t.request.name}<input name="name" required minLength={2} maxLength={120} autoComplete="name"/></label><label>{t.request.email}<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>{t.request.phone}<input name="phone" type="tel" required maxLength={40} autoComplete="tel"/></label><label>{t.request.note} <span>{t.request.optional}</span><textarea name="note" maxLength={2000} rows={3}/></label><p className="privacy">{t.request.privacy}</p>{message&&<p className="error" role="alert">{message}</p>}<button className="button" disabled={busy}>{busy?t.request.sending:t.request.submit}<ArrowUpRight size={18}/></button></form>}</DialogContent></Dialog>
<Dialog open={!!view} onOpenChange={()=>setView(null)}><DialogContent className="photo-dialog" onKeyDown={e=>{if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1);}}><DialogHeader><DialogTitle>{view?.suite.name}</DialogTitle><DialogDescription>{view?`${view.index+1} / ${view.suite.photos.length} · ${view.suite.photos[view.index].alt}`:''}</DialogDescription></DialogHeader>{view&&<div className="lightbox"><img key={view.suite.slug+view.index} src={img(view.suite,view.index)} alt={view.suite.photos[view.index].alt}/><button type="button" className="lb-nav lb-prev" onClick={()=>step(-1)} aria-label={t.lightbox.prev}><ChevronLeft size={22}/></button><button type="button" className="lb-nav lb-next" onClick={()=>step(1)} aria-label={t.lightbox.next}><ChevronRight size={22}/></button></div>}</DialogContent></Dialog></>;
}
