'use client';
import { useState } from 'react';
import StayCalendar from './stay-calendar';
import { suites, type Suite } from '@/lib/suites';
import { ArrowUpRight, ArrowRight, MapPin, Wifi, Wind, Coffee, KeyRound, BedDouble, Users, Expand, Check, Phone, Bath, ChevronLeft, ChevronRight, Images } from 'lucide-react';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const img = (s: Suite, i: number) => '/images/' + s.photos[i].file;
export default function Home(){
const [suite,setSuiteState]=useState<Suite>(suites[0]),[arrival,setArrival]=useState(''),[departure,setDeparture]=useState(''),[guests,setGuests]=useState('2'),[open,setOpen]=useState(false),[view,setView]=useState<{suite:Suite;index:number}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reference,setReference]=useState('');
function setSuite(s:Suite){setSuiteState(s);setMessage('');if(Number(guests)>s.guests)setGuests(String(s.guests));}
function chooseSuite(s:Suite){setSuite(s);document.getElementById('booking')?.scrollIntoView({behavior:'smooth',block:'start'});}
const step=(n:number)=>setView(v=>v&&{...v,index:(v.index+n+v.suite.photos.length)%v.suite.photos.length});
async function availability(e:React.FormEvent){e.preventDefault();if(!arrival||!departure){setMessage('Choose your check-in and check-out dates first.');return;}setBusy(true);setMessage('');try{const r=await fetch(`/api/availability?suite=${suite.slug}&arrival=${arrival}&departure=${departure}`);const d=await r.json() as {error:string;available?:boolean};if(!r.ok)throw Error(d.error);if(!d.available)throw Error(`These dates are unavailable in ${suite.name}. Try a different stay or another suite.`);setReference('');setOpen(true);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
async function reserve(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({suite:suite.slug,arrival,departure,guests:Number(guests),name:f.get('name'),email:f.get('email'),phone:f.get('phone'),note:f.get('note')})});const d=await r.json() as {error:string;id:string};if(!r.ok)throw Error(d.error);setReference(d.id);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
const hero=suites[0];
return <><header className="header"><a className="brand" href="/">green<span>&</span>blue<small>LUXURY SUITES · KASTELLA</small></a><nav aria-label="Main navigation"><a href="#suites">The suites</a><a href="#portside">Portside</a><a href="#saronic-pearl">Saronic Pearl</a><a href="#odyssey">Odyssey</a><a href="#location">Kastella</a></nav><a className="nav-book" href="#booking">Plan your stay <ArrowUpRight size={17}/></a></header>
<main><section className="hero"><div className="hero-copy"><p className="eyebrow">A LITTLE ATHENS. A LITTLE AEGEAN.</p><h1>Your own<br/>corner of<br/><em>Kastella.</em></h1><p className="hero-description">Slow mornings. Seaside evenings.<br/>Three thoughtfully designed suites in the heart<br className="desktop"/> of Piraeus’ most charming neighbourhood.</p><a className="text-link" href="#suites">Make yourself at home <ArrowRight size={18}/></a><div className="hero-location"><MapPin size={16}/> KASTELLA, PIRAEUS · GREECE</div></div><div className="hero-photo"><img src={img(hero,hero.cover)} alt={hero.photos[hero.cover].alt} fetchPriority="high"/><span className="photo-caption">THE PORTSIDE SUITE <span>01 / 03</span></span><button type="button" className="photo-badge" onClick={()=>setView({suite:hero,index:hero.cover})}><Expand size={18}/> Explore the space</button></div></section>
<section id="booking" className="booking-wrap"><div className="booking-intro"><p className="eyebrow">STAY A LITTLE LONGER</p><h2>Find your dates.</h2></div><form className="booking-bar" onSubmit={availability}>
<div className="suite-field"><label>SUITE</label><Select value={suite.slug} onValueChange={v=>{const s=suites.find(x=>x.slug===v);if(s)setSuite(s);}}><SelectTrigger aria-label="Choose a suite"><SelectValue/></SelectTrigger><SelectContent>{suites.map(s=><SelectItem value={s.slug} key={s.slug}>{s.name}</SelectItem>)}</SelectContent></Select></div>
<StayCalendar suite={suite} arrival={arrival} departure={departure} onChange={(a,b)=>{setArrival(a);setDeparture(b);setMessage('');}}/>
<div className="guest-field"><label>GUESTS</label><Select value={guests} onValueChange={setGuests}><SelectTrigger aria-label="Number of guests"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:suite.guests},(_,i)=>String(i+1)).map(n=><SelectItem value={n} key={n}>{n} {n==='1'?'guest':'guests'}</SelectItem>)}</SelectContent></Select></div>
<button className="button" disabled={busy}>{busy?'Checking…':'Check availability'}<ArrowUpRight size={18}/></button></form>
<p className="booking-note">Request your stay directly. Your host will confirm availability and the final price for {suite.name}.</p>{message&&!open&&<p role="alert" className="error">{message}</p>}</section>
<section id="suites" className="suites-head section"><p className="eyebrow">THREE SUITES. ONE HILLSIDE.</p><h2>Choose your<br/><em>view.</em></h2><p>Every suite has its own character, its own entrance and the same care in the details. All three sit on the hill of Profitis Ilias, a five-minute bus ride from the port.</p><nav className="suite-jump" aria-label="Suites">{suites.map((s,i)=><a key={s.slug} href={'#'+s.slug}><span>0{i+1}</span>{s.name}</a>)}</nav></section>
{suites.map((s,i)=><article key={s.slug} id={s.slug} className="suite-block section">
<div className="suite-intro"><div><p className="eyebrow">{s.eyebrow}</p><h2>{s.tagline}<br/><em>{s.taglineEm}</em></h2><p className="suite-kicker">0{i+1} · {s.name} · ★ {s.rating} on Airbnb</p></div>
<div><p>{s.summary}</p><div className="facts"><span><Expand/>{s.size} m²</span><span><Users/>{s.guests} guests</span><span><BedDouble/>{s.beds}</span><span><Bath/>{s.baths} bathroom</span></div><ul className="highlights">{s.highlights.map(h=><li key={h}><Check size={15}/>{h}</li>)}</ul><div className="suite-links"><button type="button" className="button" onClick={()=>chooseSuite(s)}>Check dates <ArrowUpRight size={18}/></button><a href={s.airbnb} target="_blank" rel="noreferrer" className="text-link">View on Airbnb <ArrowUpRight size={17}/></a></div></div></div>
<div className="gallery-grid">{s.grid.map((p,j)=><button type="button" key={p} className={'gallery-item image-'+j} onClick={()=>setView({suite:s,index:p})} aria-label={`Open photo: ${s.photos[p].alt}`}><img loading={i===0&&j===0?'eager':'lazy'} src={img(s,p)} alt={s.photos[p].alt}/></button>)}<button type="button" className="gallery-all" onClick={()=>setView({suite:s,index:0})}><Images size={16}/> Show all {s.photos.length} photos</button></div>
<div className="suite-about">{s.description.map((p,j)=><p key={j}>{p}</p>)}</div>
</article>)}
<section className="amenities section"><p className="eyebrow">THE ESSENTIALS, TAKEN CARE OF</p><div>{[[Wifi,'Stay connected','Fast Wi-Fi in every suite'],[Wind,'Keep your cool','Air conditioning'],[Coffee,'Start slowly','Equipped kitchen & coffee'],[KeyRound,'Arrive your way','Self check-in with lockbox']].map(([Icon,title,sub])=>{const I=Icon as typeof Wifi;return <article key={String(title)}><I strokeWidth={1.2}/><h3>{String(title)}</h3><p>{String(sub)}</p></article>;})}</div></section>
<section id="location" className="location section"><div className="location-name"><p className="eyebrow">PIRAEUS, WITH A LOCAL PERSPECTIVE</p><h2>Meet your<br/><em>neighbourhood.</em></h2><span>Καστέλλα</span></div><div><p>Hillside streets, harbour cafés and long evenings by the water. Kastella invites you to discover the quieter side of the city, with Athens and the islands within reach. The bus stops right outside the door.</p><div className="places"><span>01</span><div><h3>Mikrolimano</h3><p>Seafood tables and waterfront strolls, about 600 m away.</p></div></div><div className="places"><span>02</span><div><h3>Veakeio Theatre</h3><p>Open-air culture on Kastella’s hill.</p></div></div><div className="places"><span>03</span><div><h3>Piraeus & beyond</h3><p>The port, the Maritime Museum, and ferries to the islands.</p></div></div><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Riga+Fereou+28+Pireas+185+33" target="_blank" rel="noreferrer">Riga Fereou 28, Piraeus 185 33 <ArrowUpRight size={18}/></a></div></section>
<section className="closing"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>A slower stay.<br/><em>A richer experience.</em></h2><a className="button light" href="#booking">Let’s find your dates <ArrowUpRight size={18}/></a><a href="tel:+306946778666" className="call"><Phone size={16}/> +30 694 677 8666</a></section></main>
<footer><a className="brand" href="/">green<span>&</span>blue<small>LUXURY SUITES · KASTELLA</small></a><p>Riga Fereou 28 · Piraeus, Greece<br/><small>Property registration: 00003061932</small></p><div>{suites.map(s=><a key={s.slug} href={s.airbnb} target="_blank" rel="noreferrer">{s.short} on Airbnb <ArrowUpRight size={14}/></a>)}<a href="/admin">Owner access</a></div></footer>
<Dialog open={open} onOpenChange={v=>{setOpen(v);setMessage('');}}><DialogContent className="booking-dialog"><DialogHeader><DialogTitle>{reference?'Your request is on its way.':'Your Kastella stay'}</DialogTitle><DialogDescription>{reference?'Your host will contact you with the price and availability. Your reservation is not confirmed yet.':`${arrival} → ${departure} · ${guests} ${guests==='1'?'guest':'guests'} · ${suite.name}`}</DialogDescription></DialogHeader>{reference?<div className="success"><Check/><p>Request received</p><small>Reference: {reference}</small><a className="button" href="tel:+306946778666">Call your host</a></div>:<form onSubmit={reserve} className="request-form"><p>Send a booking request for {suite.name}. No payment is taken here.</p><label>Full name<input name="name" required minLength={2} maxLength={120} autoComplete="name"/></label><label>Email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Phone<input name="phone" type="tel" required maxLength={40} autoComplete="tel"/></label><label>Anything we should know? <span>(optional)</span><textarea name="note" maxLength={2000} rows={3}/></label><p className="privacy">Your contact details are shared with the property owner to respond to this request. Dates and price require the host’s confirmation.</p>{message&&<p className="error" role="alert">{message}</p>}<button className="button" disabled={busy}>{busy?'Sending…':'Request to book'}<ArrowUpRight size={18}/></button></form>}</DialogContent></Dialog>
<Dialog open={!!view} onOpenChange={()=>setView(null)}><DialogContent className="photo-dialog" onKeyDown={e=>{if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1);}}><DialogHeader><DialogTitle>{view?.suite.name}</DialogTitle><DialogDescription>{view?`${view.index+1} / ${view.suite.photos.length} · ${view.suite.photos[view.index].alt}`:''}</DialogDescription></DialogHeader>{view&&<div className="lightbox"><img key={view.suite.slug+view.index} src={img(view.suite,view.index)} alt={view.suite.photos[view.index].alt}/><button type="button" className="lb-nav lb-prev" onClick={()=>step(-1)} aria-label="Previous photo"><ChevronLeft size={22}/></button><button type="button" className="lb-nav lb-next" onClick={()=>step(1)} aria-label="Next photo"><ChevronRight size={22}/></button></div>}</DialogContent></Dialog></>;
}
