'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, MapPin, Wifi, Wind, Coffee, KeyRound, BedDouble, Users, Expand, Check, Phone } from 'lucide-react';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const listing='https://www.airbnb.gr/rooms/1413675725877220701';
export default function Home(){
const [arrival,setArrival]=useState(''),[departure,setDeparture]=useState(''),[guests,setGuests]=useState('2'),[open,setOpen]=useState(false),[photo,setPhoto]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reference,setReference]=useState('');
async function availability(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch(`/api/availability?arrival=${arrival}&departure=${departure}`);const d=await r.json() as {error:string;available?:boolean;id:string};if(!r.ok)throw Error(d.error);if(!d.available)throw Error('These dates are unavailable. Try a different stay.');setReference('');setOpen(true);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
async function reserve(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({arrival,departure,guests:Number(guests),name:f.get('name'),email:f.get('email'),phone:f.get('phone'),note:f.get('note')})});const d=await r.json() as {error:string;available?:boolean;id:string};if(!r.ok)throw Error(d.error);setReference(d.id);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
return <><header className="header"><a className="brand" href="/">green<span>&</span>blue<small>LUXURY SUITES · KASTELLA</small></a><nav aria-label="Main navigation"><a href="#suite">The suite</a><a href="#gallery">Gallery</a><a href="#location">Kastella</a></nav><a className="nav-book" href="#booking">Plan your stay <ArrowUpRight size={17}/></a></header>
<main><section className="hero"><div className="hero-copy"><p className="eyebrow">A LITTLE ATHENS. A LITTLE AEGEAN.</p><h1>Your own<br/>corner of<br/><em>Kastella.</em></h1><p className="hero-description">Slow mornings. Seaside evenings.<br/>A thoughtfully designed suite in the heart<br className="desktop"/> of Piraeus’ most charming neighbourhood.</p><a className="text-link" href="#suite">Make yourself at home <ArrowRight size={18}/></a><div className="hero-location"><MapPin size={16}/> KASTELLA, PIRAEUS · GREECE</div></div><div className="hero-photo"><img src="/images/living.jpeg" alt="The Portside suite living room, with stone feature wall and open kitchen" fetchPriority="high"/><span className="photo-caption">THE PORTSIDE SUITE <span>01 / 03</span></span><a className="photo-badge" href="#gallery"><Expand size={18}/> Explore the space</a></div></section>
<section id="booking" className="booking-wrap"><div className="booking-intro"><p className="eyebrow">STAY A LITTLE LONGER</p><h2>Find your dates.</h2></div><form className="booking-bar" onSubmit={availability}><label>CHECK-IN<input aria-label="Check-in date" required type="date" value={arrival} onChange={e=>{setArrival(e.target.value);setMessage('');}} min={new Date().toISOString().slice(0,10)}/></label><label>CHECK-OUT<input aria-label="Check-out date" required type="date" value={departure} onChange={e=>{setDeparture(e.target.value);setMessage('');}} min={arrival||new Date().toISOString().slice(0,10)}/></label><div className="guest-field"><label>GUESTS</label><Select value={guests} onValueChange={setGuests}><SelectTrigger aria-label="Number of guests"><SelectValue/></SelectTrigger><SelectContent>{['1','2','3'].map(n=><SelectItem value={n} key={n}>{n} {n==='1'?'guest':'guests'}</SelectItem>)}</SelectContent></Select></div><button className="button" disabled={busy}>{busy?'Checking…':'Check availability'}<ArrowUpRight size={18}/></button></form><p className="booking-note">Request your stay directly. Your host will confirm availability and the final price.</p>{message&&!open&&<p role="alert" className="error">{message}</p>}</section>
<section id="suite" className="suite section"><div><p className="eyebrow">CONSIDERED COMFORT. LOCAL CHARACTER.</p><h2>A place to unpack.<br/><em>A reason to linger.</em></h2></div><div><p>Welcome to The Portside. Natural textures, warm wood and a space that feels entirely your own. Settle into a peaceful corner of Kastella, with the life of Piraeus just beyond your door.</p><div className="facts"><span><Expand/>50 m²</span><span><Users/>3 guests</span><span><BedDouble/>1 bedroom</span></div><a href={listing} target="_blank" rel="noreferrer" className="text-link">Discover our Airbnb listing <ArrowUpRight size={17}/></a></div></section>
<section id="gallery" className="gallery section"><div className="section-heading"><div><p className="eyebrow">COME ON IN</p><h2>Room to feel at home.</h2></div><p>Small details. A different kind of stay.</p></div><div className="gallery-grid">{[['living.jpeg','A space to slow down','Living & dining'],['bedroom.jpeg','Thoughtfully put together','The Portside'],['detail.jpeg','The city, after hours','Piraeus at dusk']].map(([src,title,label],i)=><button key={src} className={'gallery-item image-'+i} onClick={()=>setPhoto(src)}><div><img loading="lazy" src={'/images/'+src} alt={title}/><span><Expand size={18}/></span></div><small>{label}</small><h3>{title}</h3></button>)}</div></section>
<section className="amenities section"><p className="eyebrow">THE ESSENTIALS, TAKEN CARE OF</p><div>{[[Wifi,'Stay connected','Wi-Fi'],[Wind,'Keep your cool','Air conditioning'],[Coffee,'Start slowly','Equipped kitchen'],[KeyRound,'Arrive your way','Self check-in']].map(([Icon,title,sub])=>{const I=Icon as typeof Wifi;return <article key={String(title)}><I strokeWidth={1.2}/><h3>{String(title)}</h3><p>{String(sub)}</p></article>;})}</div></section>
<section id="location" className="location section"><div className="location-name"><p className="eyebrow">PIRAEUS, WITH A LOCAL PERSPECTIVE</p><h2>Meet your<br/><em>neighbourhood.</em></h2><span>Καστέλλα</span></div><div><p>Hillside streets, harbour cafés and long evenings by the water. Kastella invites you to discover the quieter side of the city, with Athens and the islands within reach.</p><div className="places"><span>01</span><div><h3>Mikrolimano</h3><p>Seafood tables and waterfront strolls.</p></div></div><div className="places"><span>02</span><div><h3>Veakeio Theatre</h3><p>Open-air culture on Kastella’s hill.</p></div></div><div className="places"><span>03</span><div><h3>Piraeus & beyond</h3><p>Your starting point for the city and the islands.</p></div></div><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Riga+Fereou+28+Pireas+185+33" target="_blank" rel="noreferrer">Riga Fereou 28, Piraeus 185 33 <ArrowUpRight size={18}/></a></div></section>
<section className="closing"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>A slower stay.<br/><em>A richer experience.</em></h2><a className="button light" href="#booking">Let’s find your dates <ArrowUpRight size={18}/></a><a href="tel:+306946778666" className="call"><Phone size={16}/> +30 694 677 8666</a></section></main>
<footer><a className="brand" href="/">green<span>&</span>blue<small>LUXURY SUITES · KASTELLA</small></a><p>Riga Fereou 28 · Piraeus, Greece<br/><small>Property registration: 00003061932</small></p><div><a href={listing} target="_blank" rel="noreferrer">Airbnb <ArrowUpRight size={14}/></a><a href="/admin">Owner access</a></div></footer>
<Dialog open={open} onOpenChange={v=>{setOpen(v);setMessage('');}}><DialogContent className="booking-dialog"><DialogHeader><DialogTitle>{reference?'Your request is on its way.':'Your Kastella stay'}</DialogTitle><DialogDescription>{reference?'Your host will contact you with the price and availability. Your reservation is not confirmed yet.':`${arrival} → ${departure} · ${guests} guests · The Portside`}</DialogDescription></DialogHeader>{reference?<div className="success"><Check/><p>Request received</p><small>Reference: {reference}</small><a className="button" href="tel:+306946778666">Call your host</a></div>:<form onSubmit={reserve} className="request-form"><p>Send a booking request. No payment is taken here.</p><label>Full name<input name="name" required minLength={2} maxLength={120} autoComplete="name"/></label><label>Email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Phone<input name="phone" type="tel" required maxLength={40} autoComplete="tel"/></label><label>Anything we should know? <span>(optional)</span><textarea name="note" maxLength={2000} rows={3}/></label><p className="privacy">Your contact details are shared with the property owner to respond to this request. Dates and price require the host’s confirmation.</p>{message&&<p className="error" role="alert">{message}</p>}<button className="button" disabled={busy}>{busy?'Sending…':'Request to book'}<ArrowUpRight size={18}/></button></form>}</DialogContent></Dialog>
<Dialog open={!!photo} onOpenChange={()=>setPhoto(null)}><DialogContent className="photo-dialog"><DialogHeader><DialogTitle>The Portside Suite</DialogTitle><DialogDescription>Green & Blue Luxury Suites, Kastella</DialogDescription></DialogHeader>{photo&&<img src={'/images/'+photo} alt="Photo from the Green and Blue listing"/>}</DialogContent></Dialog></>;
}


