export type Lang = 'en' | 'el';
export const LANGS: Lang[] = ['en', 'el'];
export const isLang = (v: unknown): v is Lang => v === 'en' || v === 'el';
export const locale = (l: Lang) => (l === 'el' ? 'el-GR' : 'en-GB');
export const WEEKDAYS: Record<Lang, string[]> = { en: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'], el: ['Δε', 'Τρ', 'Τε', 'Πε', 'Πα', 'Σα', 'Κυ'] };
const en = {
 nav: { suites: 'The suites', kastella: 'Kastella', plan: 'Plan your stay', language: 'Language' },
 hero: { eyebrow: 'A LITTLE ATHENS. A LITTLE AEGEAN.', title: ['Your own', 'corner of', 'Kastella.'], desc1: 'Slow mornings. Seaside evenings.', desc2: 'Three thoughtfully designed suites in the heart', desc3: 'of Piraeus’ most charming neighbourhood.', cta: 'Make yourself at home', location: 'KASTELLA, PIRAEUS · GREECE', caption: 'THE PORTSIDE SUITE', explore: 'Explore the space' },
 booking: { eyebrow: 'STAY A LITTLE LONGER', title: 'Find your dates.', suite: 'SUITE', checkin: 'CHECK-IN', checkout: 'CHECK-OUT', guests: 'GUESTS', guest: (n: number) => `${n} ${n === 1 ? 'guest' : 'guests'}`, check: 'Check availability', checking: 'Checking…', note: (suite: string) => `Request your stay directly. Your host will confirm availability and the final price for ${suite}.`, pickFirst: 'Choose your check-in and check-out dates first.', unavailable: (suite: string) => `These dates are unavailable in ${suite}. Try a different stay or another suite.` },
 suites: { eyebrow: 'THREE SUITES. ONE HILLSIDE.', title: 'Choose your', titleEm: 'view.', intro: 'Every suite has its own character, its own entrance and the same care in the details. All three sit on the hill of Profitis Ilias, a five-minute bus ride from the port.', rating: (r: string) => `★ ${r} on Airbnb`, size: (m: number) => `${m} m²`, guests: (n: number) => `${n} guests`, bath: (n: number) => `${n} ${n === 1 ? 'bathroom' : 'bathrooms'}`, dates: 'Check dates', airbnb: 'View on Airbnb', allPhotos: (n: number) => `Show all ${n} photos`, openPhoto: 'Open photo' },
 amenities: { eyebrow: 'THE ESSENTIALS, TAKEN CARE OF', items: [['Stay connected', 'Fast Wi-Fi in every suite'], ['Keep your cool', 'Air conditioning'], ['Start slowly', 'Equipped kitchen & coffee'], ['Arrive your way', 'Self check-in with lockbox']] },
 location: { eyebrow: 'PIRAEUS, WITH A LOCAL PERSPECTIVE', title: 'Meet your', titleEm: 'neighbourhood.', deco: 'Καστέλλα', text: 'Hillside streets, harbour cafés and long evenings by the water. Kastella invites you to discover the quieter side of the city, with Athens and the islands within reach. The bus stops right outside the door.', places: [['Mikrolimano', 'Seafood tables and waterfront strolls, about 600 m away.'], ['Veakeio Theatre', 'Open-air culture on Kastella’s hill.'], ['Piraeus & beyond', 'The port, the Maritime Museum, and ferries to the islands.']], address: 'Riga Fereou 28, Piraeus 185 33' },
 closing: { eyebrow: 'YOUR NEXT CHAPTER STARTS HERE', title: 'A slower stay.', titleEm: 'A richer experience.', cta: 'Let’s find your dates' },
 footer: { address: 'Riga Fereou 28 · Piraeus, Greece', registration: 'Property registration', onAirbnb: (s: string) => `${s} on Airbnb`, owner: 'Owner access' },
 request: { sent: 'Your request is on its way.', title: 'Your Kastella stay', sentText: 'Your host will contact you with the price and availability. Your reservation is not confirmed yet.', received: 'Request received', reference: 'Reference', call: 'Call your host', intro: (suite: string) => `Send a booking request for ${suite}. No payment is taken here.`, name: 'Full name', email: 'Email', phone: 'Phone', note: 'Anything we should know?', optional: '(optional)', privacy: 'Your contact details are shared with the property owner to respond to this request. Dates and price require the host’s confirmation.', submit: 'Request to book', sending: 'Sending…' },
 lightbox: { prev: 'Previous photo', next: 'Next photo' },
 calendar: { selectIn: 'Select check-in date', selectOut: 'Select checkout date', nights: (n: number) => `${n} ${n === 1 ? 'night' : 'nights'} in Kastella`, addDates: (suite: string) => `Add your travel dates to check ${suite}`, minStay: 'Minimum stay: 1 night', conflict: 'Those dates aren’t available in this suite. Please choose a new stay.', checkin: 'CHECK-IN', checkout: 'CHECKOUT', addDate: 'Add date', loading: 'Checking available dates…', failed: 'We couldn’t load availability. Please try again.', retry: 'Try again', hint: 'Crossed-out dates are unavailable. Your host confirms the final price.', clear: 'Clear dates', close: 'Close', unavailable: 'unavailable', checkoutOnly: 'checkout only', prevMonth: 'Previous month', nextMonth: 'Next month', dialog: 'Choose your dates', closeCal: 'Close calendar', checkinLabel: 'Check-in', checkoutLabel: 'Check-out' },
 gate: { welcome: 'Welcome', choose: 'Choose your language', english: 'English', greek: 'Ελληνικά', note: 'You can change this at any time from the top of the page.' },
};
export type Dictionary = typeof en;
const el: Dictionary = {
 nav: { suites: 'Οι σουίτες', kastella: 'Καστέλλα', plan: 'Σχεδιάστε τη διαμονή σας', language: 'Γλώσσα' },
 hero: { eyebrow: 'ΛΙΓΗ ΑΘΗΝΑ. ΛΙΓΟ ΑΙΓΑΙΟ.', title: ['Η δική σας', 'γωνιά στην', 'Καστέλλα.'], desc1: 'Αργά πρωινά. Βραδιές δίπλα στη θάλασσα.', desc2: 'Τρεις προσεγμένες σουίτες στην καρδιά', desc3: 'της πιο γοητευτικής γειτονιάς του Πειραιά.', cta: 'Νιώστε σαν στο σπίτι σας', location: 'ΚΑΣΤΕΛΛΑ, ΠΕΙΡΑΙΑΣ · ΕΛΛΑΔΑ', caption: 'ΣΟΥΙΤΑ THE PORTSIDE', explore: 'Εξερευνήστε τον χώρο' },
 booking: { eyebrow: 'ΜΕΙΝΕΤΕ ΛΙΓΟ ΠΑΡΑΠΑΝΩ', title: 'Βρείτε τις ημερομηνίες σας.', suite: 'ΣΟΥΙΤΑ', checkin: 'ΑΦΙΞΗ', checkout: 'ΑΝΑΧΩΡΗΣΗ', guests: 'ΕΠΙΣΚΕΠΤΕΣ', guest: (n: number) => `${n} ${n === 1 ? 'επισκέπτης' : 'επισκέπτες'}`, check: 'Έλεγχος διαθεσιμότητας', checking: 'Έλεγχος…', note: (suite: string) => `Ζητήστε τη διαμονή σας απευθείας. Ο οικοδεσπότης θα επιβεβαιώσει τη διαθεσιμότητα και την τελική τιμή για το ${suite}.`, pickFirst: 'Επιλέξτε πρώτα ημερομηνίες άφιξης και αναχώρησης.', unavailable: (suite: string) => `Οι ημερομηνίες αυτές δεν είναι διαθέσιμες στο ${suite}. Δοκιμάστε άλλες ημερομηνίες ή άλλη σουίτα.` },
 suites: { eyebrow: 'ΤΡΕΙΣ ΣΟΥΙΤΕΣ. ΕΝΑΣ ΛΟΦΟΣ.', title: 'Διαλέξτε τη', titleEm: 'θέα σας.', intro: 'Κάθε σουίτα έχει τον δικό της χαρακτήρα, τη δική της είσοδο και την ίδια φροντίδα στις λεπτομέρειες. Και οι τρεις βρίσκονται στον λόφο του Προφήτη Ηλία, πέντε λεπτά με το λεωφορείο από το λιμάνι.', rating: (r: string) => `★ ${r} στο Airbnb`, size: (m: number) => `${m} τ.μ.`, guests: (n: number) => `${n} επισκέπτες`, bath: (n: number) => `${n} ${n === 1 ? 'μπάνιο' : 'μπάνια'}`, dates: 'Δείτε διαθεσιμότητα', airbnb: 'Δείτε στο Airbnb', allPhotos: (n: number) => `Όλες οι φωτογραφίες (${n})`, openPhoto: 'Άνοιγμα φωτογραφίας' },
 amenities: { eyebrow: 'ΤΑ ΑΠΑΡΑΙΤΗΤΑ, ΦΡΟΝΤΙΣΜΕΝΑ', items: [['Μείνετε συνδεδεμένοι', 'Γρήγορο Wi-Fi σε κάθε σουίτα'], ['Δροσιά όλο το καλοκαίρι', 'Κλιματισμός'], ['Ξεκινήστε αργά', 'Εξοπλισμένη κουζίνα & καφές'], ['Φτάστε όποτε θέλετε', 'Αυτόνομο check-in με lockbox']] },
 location: { eyebrow: 'ΠΕΙΡΑΙΑΣ, ΜΕ ΤΟΠΙΚΗ ΜΑΤΙΑ', title: 'Γνωρίστε τη', titleEm: 'γειτονιά σας.', deco: 'Kastella', text: 'Δρομάκια στον λόφο, καφέ στο λιμάνι και μεγάλες βραδιές δίπλα στο νερό. Η Καστέλλα σάς προσκαλεί να ανακαλύψετε την πιο ήσυχη πλευρά της πόλης, με την Αθήνα και τα νησιά σε κοντινή απόσταση. Η στάση του λεωφορείου είναι ακριβώς έξω από την πόρτα.', places: [['Μικρολίμανο', 'Ψαροταβέρνες και βόλτες στην προκυμαία, περίπου 600 μ. μακριά.'], ['Βεάκειο Θέατρο', 'Υπαίθριος πολιτισμός στον λόφο της Καστέλλας.'], ['Πειραιάς & παραπέρα', 'Το λιμάνι, το Ναυτικό Μουσείο και τα πλοία για τα νησιά.']], address: 'Ρήγα Φεραίου 28, Πειραιάς 185 33' },
 closing: { eyebrow: 'ΤΟ ΕΠΟΜΕΝΟ ΚΕΦΑΛΑΙΟ ΞΕΚΙΝΑ ΕΔΩ', title: 'Μια πιο αργή διαμονή.', titleEm: 'Μια πιο πλούσια εμπειρία.', cta: 'Ας βρούμε τις ημερομηνίες σας' },
 footer: { address: 'Ρήγα Φεραίου 28 · Πειραιάς', registration: 'Αριθμός Μητρώου Ακινήτου', onAirbnb: (s: string) => `${s} στο Airbnb`, owner: 'Είσοδος ιδιοκτήτη' },
 request: { sent: 'Το αίτημά σας στάλθηκε.', title: 'Η διαμονή σας στην Καστέλλα', sentText: 'Ο οικοδεσπότης θα επικοινωνήσει μαζί σας με την τιμή και τη διαθεσιμότητα. Η κράτησή σας δεν έχει επιβεβαιωθεί ακόμη.', received: 'Λάβαμε το αίτημά σας', reference: 'Κωδικός', call: 'Καλέστε τον οικοδεσπότη', intro: (suite: string) => `Στείλτε αίτημα κράτησης για το ${suite}. Δεν γίνεται πληρωμή εδώ.`, name: 'Ονοματεπώνυμο', email: 'Email', phone: 'Τηλέφωνο', note: 'Κάτι που πρέπει να γνωρίζουμε;', optional: '(προαιρετικό)', privacy: 'Τα στοιχεία επικοινωνίας σας κοινοποιούνται στον ιδιοκτήτη για να απαντήσει στο αίτημα. Οι ημερομηνίες και η τιμή απαιτούν επιβεβαίωση από τον οικοδεσπότη.', submit: 'Αίτημα κράτησης', sending: 'Αποστολή…' },
 lightbox: { prev: 'Προηγούμενη φωτογραφία', next: 'Επόμενη φωτογραφία' },
 calendar: { selectIn: 'Επιλέξτε ημερομηνία άφιξης', selectOut: 'Επιλέξτε ημερομηνία αναχώρησης', nights: (n: number) => `${n} ${n === 1 ? 'νύχτα' : 'νύχτες'} στην Καστέλλα`, addDates: (suite: string) => `Προσθέστε ημερομηνίες για να ελέγξετε το ${suite}`, minStay: 'Ελάχιστη διαμονή: 1 νύχτα', conflict: 'Οι ημερομηνίες αυτές δεν είναι διαθέσιμες σε αυτή τη σουίτα. Επιλέξτε νέα διαμονή.', checkin: 'ΑΦΙΞΗ', checkout: 'ΑΝΑΧΩΡΗΣΗ', addDate: 'Προσθήκη', loading: 'Έλεγχος διαθέσιμων ημερομηνιών…', failed: 'Δεν ήταν δυνατή η φόρτωση της διαθεσιμότητας. Δοκιμάστε ξανά.', retry: 'Δοκιμάστε ξανά', hint: 'Οι διαγραμμένες ημερομηνίες δεν είναι διαθέσιμες. Ο οικοδεσπότης επιβεβαιώνει την τελική τιμή.', clear: 'Καθαρισμός', close: 'Κλείσιμο', unavailable: 'μη διαθέσιμη', checkoutOnly: 'μόνο για αναχώρηση', prevMonth: 'Προηγούμενος μήνας', nextMonth: 'Επόμενος μήνας', dialog: 'Επιλέξτε ημερομηνίες', closeCal: 'Κλείσιμο ημερολογίου', checkinLabel: 'Άφιξη', checkoutLabel: 'Αναχώρηση' },
 gate: { welcome: 'Καλώς ήρθατε', choose: 'Επιλέξτε γλώσσα', english: 'English', greek: 'Ελληνικά', note: 'Μπορείτε να την αλλάξετε ανά πάσα στιγμή από το πάνω μέρος της σελίδας.' },
};
export const dictionaries: Record<Lang, Dictionary> = { en, el };
