// Generated from the Airbnb listings' photo sets. Paths are relative to /images/.
export type Photo = { file: string; alt: string; portrait?: boolean };
export const photos: Record<string, Photo[]> = {
 'portside': [
  { file: 'portside/01.jpg', alt: "Bright Open-Plan Living Room with Smart TV" },
  { file: 'portside/02.jpg', alt: "Modern Living Area with Elegant Stone Accent Wall" },
  { file: 'portside/03.jpg', alt: "Sunset View from the Property Balcony" },
  { file: 'portside/04.jpg', alt: "Stylish Lounge Space with Comfortable Sofa and Dining Area", portrait: true },
  { file: 'portside/05.jpg', alt: "Contemporary Living Room with Minimalist Design" },
  { file: 'portside/06.jpg', alt: "Cozy Living Space with Natural Light and Modern Decor" },
  { file: 'portside/07.jpg', alt: "Spacious Living Room with Artistic Touches and TV" },
  { file: 'portside/08.jpg', alt: "Elegant Studio Interior with Wooden Divider Feature" },
  { file: 'portside/09.jpg', alt: "Bright Bedroom with Soft Lighting and Comfortable Bedding" },
  { file: 'portside/10.jpg', alt: "Bright Bedroom with Soft Lighting and Comfortable Bedding" },
  { file: 'portside/11.jpg', alt: "Welcome Sign at Green & Blue Castella Luxury Suites" },
  { file: 'portside/12.jpg', alt: "Fresh Towels Prepared for Your Stay" },
  { file: 'portside/13.jpg', alt: "View of the interior" },
  { file: 'portside/14.jpg', alt: "Sleek Modern Kitchen with Full Amenities" },
  { file: 'portside/15.jpg', alt: "Coffee Station with Espresso Machine and Complimentary Coffee" },
  { file: 'portside/16.jpg', alt: "Modern Bathroom with Walk-In Shower and Vanity" },
  { file: 'portside/17.jpg', alt: "Decorative Candles and Relaxing Ambience Details", portrait: true },
  { file: 'portside/18.jpg', alt: "Elegant Decorative Tray with Coastal-Inspired Details" },
  { file: 'portside/19.jpg', alt: "Comfortable Bedroom with Modern Furnishings" },
  { file: 'portside/20.jpg', alt: "Cozy Bedroom with Soft Textures and Warm Lighting" },
  { file: 'portside/21.jpg', alt: "Bright Bedroom with Minimalist Design and Natural Light" },
  { file: 'portside/22.jpg', alt: "Comfortable Twin Bedroom Setup with Modern Decor", portrait: true },
  { file: 'portside/23.jpg', alt: "Stylish Bedside Decor and Reading Lamp", portrait: true },
  { file: 'portside/24.jpg', alt: "Stylish Entrance Decor with Mirror and Greenery", portrait: true },
  { file: 'portside/25.jpg', alt: "Decorative details of the interior", portrait: true },
  { file: 'portside/26.jpg', alt: "Modern Living Area with Smart TV and Contemporary Decor" },
  { file: 'portside/27.jpg', alt: "Entrance Workspace and Storage Area" },
  { file: 'portside/28.jpg', alt: "Comfortable Bedroom with Elegant Neutral Tones" },
  { file: 'portside/29.jpg', alt: "Entrance of the property - View of the interior" },
  { file: 'portside/30.jpg', alt: "Evening Exterior View with Ambient Lighting" },
  { file: 'portside/31.jpg', alt: "Evening Exterior View with Ambient Lighting" },
  { file: 'portside/32.jpg', alt: "Modern Bathroom with Contemporary Sink and Mirror", portrait: true },
  { file: 'portside/33.jpg', alt: "Exterior View of the Property Entrance" },
  { file: 'portside/34.jpg', alt: "High-Speed Wi-Fi Available Throughout the Property", portrait: true },
  { file: 'portside/35.jpg', alt: "Sunset hour at the property - Majestic City Views" },
 ],
 'saronic-pearl': [
  { file: 'saronic-pearl/01.jpg', alt: "Modern Open-Plan Living Area with Sofa Bed and Smart TV" },
  { file: 'saronic-pearl/02.jpg', alt: "Stylish Bedroom with Double Bed and Soft Lighting" },
  { file: 'saronic-pearl/03.jpg', alt: "Scenic Elevated Views over Piraeus and the Coastline" },
  { file: 'saronic-pearl/04.jpg', alt: "Bright Living Room with Modern Furnishings" },
  { file: 'saronic-pearl/05.jpg', alt: "Cozy Living Area with Smart TV and Dining Table" },
  { file: 'saronic-pearl/06.jpg', alt: "Sunset View over the City and Port" },
  { file: 'saronic-pearl/07.jpg', alt: "Fully Equipped Kitchen with Modern Appliances" },
  { file: 'saronic-pearl/08.jpg', alt: "Elegant Open-Plan Lounge and Kitchen Space" },
  { file: 'saronic-pearl/09.jpg', alt: "Minimalist Bedroom with Comfortable Double Bed" },
  { file: 'saronic-pearl/10.jpg', alt: "Coffee Machine and Complimentary Coffee Amenities" },
  { file: 'saronic-pearl/11.jpg', alt: "Listing image 11" },
  { file: 'saronic-pearl/12.jpg', alt: "Comfortable Bedroom with Clean Minimal Design" },
  { file: 'saronic-pearl/13.jpg', alt: "Stylish Vanity Corner with Decorative Mirror", portrait: true },
  { file: 'saronic-pearl/14.jpg', alt: "Comfortable Lounge Chair Corner with Ambient Lighting", portrait: true },
  { file: 'saronic-pearl/15.jpg', alt: "Decorative Vanity Area with Mirror and Storage", portrait: true },
  { file: 'saronic-pearl/16.jpg', alt: "Spacious Bathroom with Modern Walk-In Shower" },
  { file: 'saronic-pearl/17.jpg', alt: "Elegant Bathroom with Premium Finishes", portrait: true },
  { file: 'saronic-pearl/18.jpg', alt: "Contemporary Bathroom with Walk-In Shower and LED Lighting", portrait: true },
  { file: 'saronic-pearl/19.jpg', alt: "Panoramic City and Sea View from the Property" },
  { file: 'saronic-pearl/20.jpg', alt: "Private Entrance with Contemporary Architecture", portrait: true },
  { file: 'saronic-pearl/21.jpg', alt: "Sleek Modern Kitchen with Built-In Appliances" },
  { file: 'saronic-pearl/22.jpg', alt: "Fresh Towels and Hotel-Style Linen Provided" },
  { file: 'saronic-pearl/23.jpg', alt: "Green & Blue Castella Luxury Suites Welcome Sign", portrait: true },
  { file: 'saronic-pearl/24.jpg', alt: "Beautiful Coastal and Cityscape View Nearby" },
  { file: 'saronic-pearl/25.jpg', alt: "Entrance Sign of Green & Blue Castella Luxury Suites" },
  { file: 'saronic-pearl/26.jpg', alt: "Cozy Outdoor Exterior Area at Night" },
  { file: 'saronic-pearl/27.jpg', alt: "Modern Exterior Lighting and Private Entrance" },
  { file: 'saronic-pearl/28.jpg', alt: "Contemporary Exterior of the Luxury Suites" },
  { file: 'saronic-pearl/29.jpg', alt: "Modern Exterior View of the Property by Day" },
  { file: 'saronic-pearl/30.jpg', alt: "Elegant Night View of the Property Exterior" },
 ],
 'odyssey': [
  { file: 'odyssey/01.jpg', alt: "Spacious Bedroom with Modern Interior Design" },
  { file: 'odyssey/02.jpg', alt: "Stylish Living Room with Modern Furnishings" },
  { file: 'odyssey/03.jpg', alt: "Elegant Bedroom with Soft Lighting and Contemporary Decor" },
  { file: 'odyssey/04.jpg', alt: "Fully Equipped Modern Kitchen with Stone Details" },
  { file: 'odyssey/05.jpg', alt: "Balcony Seating Area with Panoramic City Views" },
  { file: 'odyssey/06.jpg', alt: "Bright Living Room with Dining Area and Natural Light" },
  { file: 'odyssey/07.jpg', alt: "Elegant Living Area with Comfortable Seating" },
  { file: 'odyssey/08.jpg', alt: "Bright Open-Plan Living Room with Balcony Access" },
  { file: 'odyssey/09.jpg', alt: "Relaxing Lounge Area with Comfortable Seating" },
  { file: 'odyssey/10.jpg', alt: "Modern Bedroom with Elegant Decor and Smart TV" },
  { file: 'odyssey/11.jpg', alt: "Bright Kitchen Area with Dining Table and Natural Light" },
  { file: 'odyssey/12.jpg', alt: "Sleek Kitchen Area with Contemporary Appliances" },
  { file: 'odyssey/13.jpg', alt: "Stylish Open Kitchen with Dining Space" },
  { file: 'odyssey/14.jpg', alt: "Decorative Kitchen Details with Modern Touches" },
  { file: 'odyssey/15.jpg', alt: "Bright Kitchen Area with Dining Table and Natural Light" },
  { file: 'odyssey/16.jpg', alt: "Modern Kitchen with Elegant Stone Wall Design" },
  { file: 'odyssey/17.jpg', alt: "Coffee Station with Espresso Machine and Complimentary Coffee" },
  { file: 'odyssey/18.jpg', alt: "In-Room Coffee and Refreshment Amenities" },
  { file: 'odyssey/19.jpg', alt: "Living Room with Balcony and Relaxing Seating Area" },
  { file: 'odyssey/20.jpg', alt: "Double Bedroom Setup with Minimalist Style" },
  { file: 'odyssey/21.jpg', alt: "Cozy Bedroom with Contemporary Design" },
  { file: 'odyssey/22.jpg', alt: "In-Room Coffee and Refreshment Amenities", portrait: true },
  { file: 'odyssey/23.jpg', alt: "Modern Bathroom with Walk-In Shower and Vanity" },
  { file: 'odyssey/24.jpg', alt: "Cozy Evening Living Room Ambience" },
  { file: 'odyssey/25.jpg', alt: "Coffee Station with Espresso Machine and Complimentary Coffee", portrait: true },
  { file: 'odyssey/26.jpg', alt: "Comfortable Bedroom with Warm Wooden Accents" },
  { file: 'odyssey/27.jpg', alt: "Spacious Bathroom with Elegant Marble Finishes" },
  { file: 'odyssey/28.jpg', alt: "Contemporary Bathroom with Bright Mirror Lighting" },
  { file: 'odyssey/29.jpg', alt: "Stylish Bathroom with Modern Sink and Shower Area", portrait: true },
  { file: 'odyssey/30.jpg', alt: "Panoramic City and Sea Views from the Property" },
  { file: 'odyssey/31.jpg', alt: "Stylish Exterior Entrance at Night" },
  { file: 'odyssey/32.jpg', alt: "Stunning Views Over Piraeus and the Coastline" },
  { file: 'odyssey/33.jpg', alt: "Welcome Sign at Green & Blue Castella Luxury Suites" },
  { file: 'odyssey/34.jpg', alt: "Fresh Towels Prepared for Your Stay" },
  { file: 'odyssey/35.jpg', alt: "Modern Hallway Entrance with Ambient Lighting" },
  { file: 'odyssey/36.jpg', alt: "Exterior View of the Building Entrance" },
  { file: 'odyssey/37.jpg', alt: "Evening Exterior Ambience with Warm Lighting" },
  { file: 'odyssey/38.jpg', alt: "Scenic City and Sea View from Above" },
  { file: 'odyssey/39.jpg', alt: "Decorative Kitchen Details with Modern Touches" },
  { file: 'odyssey/40.jpg', alt: "Beautiful Sunset Views from the Area" },
  { file: 'odyssey/41.jpg', alt: "Modern Ceiling Design with Ambient Lighting" },
  { file: 'odyssey/42.jpg', alt: "Sunset Skyline Views Over the City" },
  { file: 'odyssey/43.jpg', alt: "Welcome Treats and Complimentary Amenities" },
  { file: 'odyssey/44.jpg', alt: "High-Speed Wi-Fi Available Throughout the Property", portrait: true },
 ],
};
